name: amtt
description: "크래프톤 아마따 프로젝트"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker:
  intl:
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  firebase_messaging:
  firebase_analytics:
  googleapis_auth:
  firebase_admin:
  flutter_local_notifications:
  flutter_email_sender:
  http:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/secret_key.json
    - assets/secret.json

web:
  assets:
    - assets/firebase-messaging-sw.js



