name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Create Firebase Configuration File
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json

      - name: Create secret_key.json
        run: |
          mkdir -p assets
          echo "${{ secrets.SECRET_KEY_JSON }}" > assets/secret_key.json
          echo "${{ secrets.SECRET_JSON }}" > assets/secret.json

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk